
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-flores
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: unless-stopped
